---
version: "3.1"
services:
  arrt-dl:
    image: tvanicraath/arrt-dl
    container_name: arrt-dl
    environment:
      - LOGGING_LEVEL=INFO

      - TMDB_API_KEY={your key}
      - YOUTUBE_API_KEY={your key}

      - FLASK_PORT=5000
      - ARIA2_HOST=http://localhost #Once yt-dlp adds support for aria2 using RPC, will allow external aria2 client
      - RPC_PORT=6800
      - RPC_SECRET=80tiny39goodyogurt #Or set your own secret
      - DOWNLOAD_DIRECTORY=/data/torrents/aria2

    volumes:
      - {path to data in your host}:/data     #path to data. aria2 will place downloads in /data/torrents/aria2/

    ports:  #some of these ports are hard coded. do not change for now.
      - 5000:5000 #flask api
      - 6800:6800 #aria2c rpc
      - 6888:6888 #aria2c transfers
      - 6888:6888/udp
    restart: unless-stopped



  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    ports:
     - 6884:6880
    restart: unless-stopped